const curatedTagBank = {
  Tops: [
    "long sleeve",
    "short sleeve",
    "sleeveless",
    "tank",
    "crop top",
    "graphic",
    "knit",
    "ribbed",
    "button down",
    "oversized",
    "v-neck",
    "crew neck",
    "square neck",
    "lace",
    "sheer",
    "blouse",
    "peplum",
    "statement",
    "stretchy",
    "lightweight",
  ],
  Bottoms: [
    "high-waisted",
    "mid-rise",
    "low-rise",
    "wide leg",
    "straight leg",
    "skinny",
    "flare",
    "joggers",
    "cargo",
    "mini skirt",
    "maxi skirt",
    "midi skirt",
    "denim",
    "stretchy",
    "athletic",
    "tailored",
    "linen",
    "casual",
    "formal",
    "comfortable",
  ],
  Dresses: [
    "midi",
    "maxi",
    "mini",
    "bodycon",
    "wrap",
    "a-line",
    "cocktail",
    "summer",
    "formal",
    "casual",
    "flowy",
    "ribbed",
    "stretchy",
    "boho",
    "cottagecore",
    "sleeveless",
    "long sleeve",
    "v-neck",
    "holiday",
    "wedding guest",
  ],
  Outerwear: [
    "puffer",
    "fleece",
    "denim jacket",
    "leather jacket",
    "lightweight",
    "trench",
    "oversized",
    "bomber",
    "windbreaker",
    "hooded",
    "quilted",
    "warm",
    "cozy",
    "lined",
    "utility",
    "zip-up",
    "button-up",
    "water-resistant",
    "casual",
    "classic",
  ],
  Activewear: [
    "athletic",
    "moisture-wicking",
    "running",
    "yoga",
    "gym",
    "high-stretch",
    "breathable",
    "cropped",
    "supportive",
    "compression",
    "biker shorts",
    "sport bra",
    "tennis skirt",
    "leggings",
    "squat-proof",
    "quick-dry",
    "soft-touch",
    "lightweight",
    "performance",
    "training",
  ],
  Shoes: [
    "sneakers",
    "heels",
    "sandals",
    "boots",
    "flats",
    "platform",
    "slip-on",
    "comfy",
    "leather",
    "vegan",
    "ankle boots",
    "running shoes",
    "dress shoes",
    "strappy",
    "chunky heel",
    "wedge",
    "statement",
    "neutral",
    "casual",
    "comfort fit",
  ],
  Accessories: [
    "minimalist",
    "statement",
    "gold-tone",
    "silver-tone",
    "trendy",
    "classic",
    "layering",
    "stackable",
    "adjustable",
    "lightweight",
    "everyday",
    "boho",
    "bold",
    "chic",
    "earrings",
    "necklace",
    "bracelet",
    "hair accessory",
    "belt",
    "giftable",
  ],
  Bags: [
    "crossbody",
    "tote",
    "shoulder bag",
    "mini bag",
    "structured",
    "soft leather",
    "vegan",
    "nylon",
    "travel",
    "zip closure",
    "bucket bag",
    "convertible",
    "quilted",
    "classic",
    "evening bag",
    "trendy",
    "neutral",
    "everyday",
    "work bag",
    "hands-free",
  ],
  "Home Goods": [
    "minimalist",
    "boho design",
    "neutral tones",
    "cozy",
    "giftable",
    "accent decor",
    "dresser organization",
    "kitchen",
    "bath",
    "modern",
    "functional",
    "trendy",
    "small space",
    "lightweight",
    "seasonal",
    "holiday",
    "storage",
    "natural materials",
    "soft touch",
    "cute",
  ],
  "Beauty & Grooming": [
    "clean beauty",
    "hydrating",
    "matte finish",
    "glowy",
    "multi-use",
    "travel size",
    "skincare",
    "makeup",
    "gentle",
    "fragrance-free",
    "viral",
    "long lasting",
    "buildable",
    "pigmented",
    "hydrating formula",
    "lightweight",
    "everyday",
    "luxury",
    "gift set",
    "trending",
  ],
  "Kids & Baby": [
    "soft",
    "stretchy",
    "playtime",
    "adorable",
    "cozy",
    "gentle fabric",
    "matching set",
    "neutral",
    "durable",
    "comfortable",
    "school",
    "seasonal",
    "giftable",
    "lightweight",
    "easy care",
    "washable",
    "cute print",
    "practical",
    "active",
    "classic",
  ],
  "Toys & Games": [
    "STEM",
    "educational",
    "creative",
    "imagination",
    "classic toy",
    "hands-on",
    "multi-skill",
    "active play",
    "colorful",
    "indoor",
    "outdoor",
    "giftable",
    "durable",
    "kid-approved",
    "multi-piece",
    "safe",
    "beginner-friendly",
    "fine motor",
    "interactive",
    "fun",
  ],
  Electronics: [
    "tech",
    "portable",
    "lightweight",
    "charging",
    "wireless",
    "compact",
    "newer model",
    "tested",
    "working",
    "accessory included",
    "smart",
    "battery",
    "great condition",
    "functional",
    "usb",
    "bluetooth",
    "everyday",
    "gaming",
    "streaming",
    "clean",
  ],
  Media: [
    "collector",
    "bestseller",
    "classic",
    "giftable",
    "family-friendly",
    "new release",
    "complete set",
    "limited edition",
    "fan favorite",
    "easy read",
    "popular",
    "trending",
    "hardcover",
    "paperback",
    "must-have",
    "clean copy",
    "kid-friendly",
    "adult fiction",
    "romance",
    "thriller",
  ],
  Other: [
    "unique",
    "giftable",
    "rare find",
    "minimalist",
    "simple",
    "neutral",
    "everyday use",
    "classic",
    "lightweight",
    "versatile",
    "practical",
    "multi-purpose",
    "cute",
    "modern",
    "compact",
    "easy care",
    "travel-ready",
    "trendy",
    "functional",
    "essential",
  ],
};

export const getCuratedTags = (category) => curatedTagBank[category] || [];
export default curatedTagBank;
